### ISSUE TITLE
MRO / environment - branch mgmt is NOT resilient / idempotent on dev

### ISSUE THREAD

**Issue by clemensutschig** [opendevstack/ods-mro-jenkins-shared-library#160]
In *very* certain cornercases - there may not be branches on all components (e.g. in case someone deleted them?!). in this case the phaseInit / checkout will fail, because it starts with the passed "version" to checkout all the release branches on the components.

Here (and only on dev) - we need resilience - that is in case the branch is not found, fall back to the configured one.. at the end of the run, the new branch will be configured anyway :;)

**Comment by michaelsauter** [comment]
So here are my thoughts on how this can happen:

* Release branch manually created in the release manager repo, BEFORE a pipeline run, and when no release branches are manually created for the linked repos
* A repo is added to the `metadata.yml` file on a release branch, and the added repo does not have the same release branch
* Branch is deleted

All of these cases are "user error". Therefore I am not entirely sure if we should auto-fix it. Maybe it would be better to display a nice error message that mentions possible reasons why a checkout was not successful, so that the user can fix appropriately themselves?

**Comment by michaelsauter** [comment]
You convinced me to just do the checkout from the configured branch - I can't think of a scenario where this is not wanted.
